### PR TITLE
fix: typescript definition for Button's onPress should have event as argument

### PR DESCRIPTION
**Pull request by abumalick**
typescript definition for Button's onPress should have event as argument

### CODE REVIEW

**Comment by RichardLindhout** [comment]
This should be done for all components inclusing list.Item e.g. everything with onPress

**Comment by abumalick** [comment]
I am ok to make more fixes if I get positive feedback from maintainers.

I am a bit surprised that a simple change like this does not get any feedback for a month.

Maybe I did something wrong?

**Comment by lukewalczak** [comment]
Hey @abumalick don't worry, I will review the PR in my spare time

**Comment by lukewalczak** [comment]
> This should be done for all components inclusing list.Item e.g. everything with onPress

@RichardLindhout would you like to handle that in the separate PR?

**Comment by RichardLindhout** [comment]
@lukewalczak done!

**Review by lukewalczak — APPROVED** [review]
Thanks @abumalick

**Pull request merged**
