### PR TITLE
feat: add alternative text to avatar image

### PR DESCRIPTION
**Pull request by StheffanyHadlich**
### Summary

This PR is an attempt to solve #2022. It exchanges `Avatar.Image` for a provided text when the image source isn't defined

### CODE REVIEW

**Comment by aprilmintacpineda** [comment]
Can this PR also include https://github.com/callstack/react-native-paper/issues/1066?

**Comment by StheffanyHadlich** [comment]
> Can this PR also include #1066?

I added the props `onError`and `onLoad` to the component. I also changed `alt` to `accessibilityLabel` because  it seems to fit better the request on #1066.  As it is you can pass those two props to regulate when it will show `AvatarImage` or `AvatarText`, let me know if you need any changes here

**Comment by Trancever** [comment]
@StheffanyHadlich Could you rebase your PR or create a new one? Sorry for the inconvenience but in the meantime we switched master with 4.0 and the git history is a bit broken now for old PRs :/

**Comment by StheffanyHadlich** [comment]
> @StheffanyHadlich Could you rebase your PR or create a new one? Sorry for the inconvenience but in the meantime we switched master with 4.0 and the git history is a bit broken now for old PRs :/

due the amount of updates I'm opening a new one

**Pull request closed without merging**
