### PR TITLE
Typography: Add Letter spacing

### PR DESCRIPTION
**Pull request by z0al**
### Motivation

Follow the spec regarding letter-spacing: https://material.io/design/typography/the-type-system.html#type-scale

I modified the letter-spacing of the following components:

| Component | Letter-spacing |
|:-----------------|:---------------------|
|  Headline (H5)   |  0         |
|  Title (H6)   |  0.15         |
|  Subheading (Body 1)   |  0.5         |
|  Paragraph (Body 2)   |  0.25         |
|  Caption   |  0.4         |

### Test plan

This requires visual testing.

**Before:**

Screenshot_20190606-160010__01

**After:**

Screenshot_20190606-160338__01

### CODE REVIEW

**Comment by z0al** [comment]
Taking a look again at the spec, it seems I skipped the "Letter spacing units" section. I'm not sure if there is something doable there tough.

**Comment by z0al** [comment]
Is there is anything I need to do to help review this?

**Comment by Trancever** [comment]
@satya164 Is it possible you could have a look at this?

**Comment by Trancever** [comment]
@z0al Thanks, looks good!

**Pull request merged**
