### PR TITLE
feat: prop to specify capitalization on button text

### PR DESCRIPTION
**Pull request by JohnKanev**
A simple prop that can specify if the text in a button should be capitalized or not.

The prop will be:
upperCase?: boolean // default value true

### CODE REVIEW

**Comment by ferrannp** [comment]
@JohnKanev can you fix the build so we can merge this?

**Comment by Hunsu** [comment]
Why the default value is true? This can break existing users. And do we really need this? I think we should keep the components simple but allow people to extends them to fulfill their use cases. For this one you just create your own components that passes the capitalized text to this buttons.

**Comment by Trancever** [comment]
@Hunsu All the buttons in material design guidelines are uppercase, that's why the default value is true.

**Comment by JohnKanev** [comment]
Sorry guys I have been on a long vacation.

The truth is that I made this pull request is because most of my clients ask for everything to not be upcase because of some psychology studies.

I will create a new pull request later on no problem.

**Pull request closed without merging**
