### PR TITLE
fix: Card correct animation drivers

### LINKED ISSUE #2138: Card elevation animation is not correct on Dark Adaptive Mode
# PR submitted

fixed with #2113 

### Current behaviour

Currently the press in/out animation of Cards in the Dark Adaptive mode only animates the color with an overlay.

#### Before press
normal

#### Current overlay press
ovelay

### Expected behaviour

Use scale animation.

#### Expected overlay and scale

scale_and_overlay

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.62
| react-native-paper    | 4.0.1
| react-native-vector-icons | 7.0.0

### PR DESCRIPTION
**Pull request by PedroBern**
### Summary

#2068 was a partial solution for #2063, bug introduced in #1783.

It did solve in case of toggling the theme while there is no animations running, **but if a card is animating during the process** it may (in case of adaptive mode) receive the animation with native drivers and break in the `Surface` component, just as before of #2068.

**[update]**: Just to clarify the "may receive the animation",  the previous one may be with native drivers `true`, then toggling the theme while animating may change the animation to native drivers `false`, but it is not possible to change native drivers of a an animation during an animation, it does breaks the app.

This PR solves this issue, now you can even toggle the theme with `<Card onPress={toggleTheme}>...` which wasn't possible before (with adaptive mode).

~~**[update 2]** Now it fix #2138 too, this is particularly useful if the card is just an image, as in this case there is no feedback when you press it on dark adaptive mode.~~

### Test plan

Try the following code, before and after this PR. Before, it will break.

```jsx
<Card onPress={toggleTheme}>{children}</Card>
```

### CODE REVIEW

**Comment by Trancever** [comment]
@PedroBern Thanks for your contribution! 

I have a question regarding card scaling. Could you point me to a place in MD Guidelines with the spec for scaling surfaces in the dark mode? I've tried looking for it but found only this https://material.io/design/color/dark-theme.html#ui-application and they recommend to only change the surface color.

**Comment by PedroBern** [comment]
@Trancever  you are right, there is no guideline for this, Im sorry! But maybe I can set the default to 1 (no scale) making it optional, or if you want I can remove this conpletely from the pr.

**Comment by Trancever** [comment]
@PedroBern I think it's best to remove it completely from the PR and limit the scope of this PR just to fixing the issue with animation. Thanks in advance!

**Comment by PedroBern** [comment]
@Trancever ok perfect :)

**Comment by PedroBern** [comment]
@Trancever already done, reverted the commits :)

**Comment by kamui545** [comment]
@PedroBern Would it be possible to update the PR to resolve the conflicts? It looks like the component got refactored to FC (v4.2.0).

If you don't have time just let me know, I can work on a new PR (I just don't want to steal the credits).

It would be nice to have this merged, I've been using this patch with `patch-package` for a month and it's working great, I am not seeing any regressions or side effects.

**Comment by PedroBern** [comment]
@kamui545 thanks for the call :) Please go ahead with a new PR then.

**Comment by kamui545** [comment]
Okay, so it looks like I am too retarded to port this fix to React.FC...
No idea why, but it won't work. Questioning my whole career right now... 😂

**Comment by PedroBern** [comment]
@kamui545  It must be something we are not seeing, I did a quick try now and didn't work too! But I don't have time to investigate at the moment... Maybe in the future!

**Review by OlimpiaZurek — APPROVED** [review]

**Comment by tellodaniel** [comment]
This will be addressed or merge soon? @OlimpiaZurek 

Thanks!

**Comment by lukewalczak** [comment]
> there are quite a few conflicts, probably not worth fixing it. Feel free to close or reference in new issue/pr if this is still relevant.

Thanks @PedroBern for your work and commitment. Based on your PR I will open a fresh one _(to avoid rebasing and resolving conflicts)_ along with tests and new example.

**Pull request closed without merging**
