### PR TITLE
Expo39 Kitchen Sink

### PR DESCRIPTION
**Pull request by Quantmatic**
### Summary

# React Native Paper Kitchen Sink 

tab navigation with Fab + drawer with navigation + themed up + complete examples

thanks to Alex Melnyk for his clipped tabbar
https://github.com/alex-melnyk/clipped-tabbar

thanks to Dawid Urbaniak for his twitterClone
https://github.com/Trancever/twitterClone

thanks to @callstack for being awesome

### Test plan

If you want to run the example from the repo,

- Clone the repository and run `yarn bootstrap` in the root
- Run `yarn example_expo39 start` to start the packager
- Follow the instructions to open it with the [Expo app](https://expo.io/)

- alternatively you can run `cd example_expo39 && yarn install`
- followed by `yarn start`

### CODE REVIEW

**Comment by Trancever** [comment]
@Quantmatic Could you elaborate more on what is this PR adding? It changes 11k lines of code, it's literally not reviewable.

**Comment by Quantmatic** [comment]
> @Quantmatic Could you elaborate more on what is this PR adding? It changes 11k lines of code, it's literally not reviewable.

It's just an updated [example] directory, with more flare, got all the navigation variants, doesn't give any yellow warnings with expo39

It changes nothing... just cleaned up kitchen sink of all the react-native-paper elements with all react-native navigation elements

**Comment by Trancever** [comment]
@Quantmatic We can't merge the PR as it is now, it's too big. Could you split it into smaller chunks? For example, the first PR could migrate the example app to the newest expo sdk 40. Then we could start fixing the warnings. What do you think?

**Comment by Quantmatic** [comment]
> @Quantmatic We can't merge the PR as it is now, it's too big. Could you split it into smaller chunks? For example, the first PR could migrate the example app to the newest expo sdk 40. Then we could start fixing the warnings. What do you think?

Definitely, I can do it over the weekend if that works.

**Comment by Trancever** [comment]
@Quantmatic Awesome! Thank you.

**Comment by Trancever** [comment]
@Quantmatic I will close this PR for now. Please create new ones with a well-defined scope, fixing one issue at a time. Thank you!

**Pull request closed without merging**
