### PR TITLE
feat: added testID to TextInput component

### PR DESCRIPTION
**Pull request by mguardarini**
### Motivation
Add testID prop to TextInput component so it can be used in testing tools.

### CODE REVIEW

**Comment by fabiodamasceno** [comment]
Testing with user centric tooling like testing library may be hard without testID. I agree.

**Comment by fabiodamasceno** [comment]
@mguardarini can you add you new property to documentation?

**Comment by mguardarini** [comment]
> @mguardarini can you add you new property to documentation?

yes, the library uses component-docs to generate the documentation and the update occurs when the [pipeline](https://circleci.com/gh/callstack/react-native-paper/16433?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is executed.

**Comment by gehan** [comment]
👍

**Comment by Trancever** [comment]
Btw, is this change even needed? Paper's TextInput props extend React Native's TextInput that already supports testID prop. I believe passing testID should work even without this change. @mguardarini Can you confirm this?

**Comment by Trancever** [comment]
Please reopen this if needed. I am closing this, cause I am pretty sure it's not needed and this prop is already supported.

**Pull request closed without merging**
