### PR TITLE
Fix: Proper RTL support

### LINKED ISSUE #375: Proper RTL support

### PR DESCRIPTION
**Pull request by iyadthayyil**
### TODO

- [x] BottomNavigation
- [x] Button
- [x] Caption
- [x] Card
- [x] CardActions
- [x] CardContent
- [x] CardCover
- [x] Checkbox
- [x] Chip
- [x] Dialog
- [x] DialogActions
- [x] DialogContent
- [x] DialogScrollArea
- [x] DialogTitle
- [x] Divider
- [x] DrawerItem
- [x] DrawerSection
- [x] FAB
- [x] FABGroup
- [x] Headline
- [ ] HelperText
- [x] ListAccordion
- [x] ListItem
- [x] ListSection
- [x] Modal
- [x] Paper
- [x] Paragraph
- [x] ProgressBar
- [x] RadioButton
- [x] RadioButtonGroup
- [x] Searchbar
- [x] Snackbar
- [x] Subheading
- [x] Switch
- [x] Text
- [ ] TextInput
- [x] Title
- [x] Appbar
- [x] AppbarAction
- [x] AppbarBackAction
- [x] AppbarContent
- [x] TouchableRipple
- [x] Icons

fixes #375

### CODE REVIEW

**Comment by ferrannp** [comment]
@iyadthayyil are you still working on this? This is quite important for v2.

**Comment by iyadthayyil** [comment]
@ferrannp Most components are already RTL supported, except few like texts, icons, textInput and searchBar.
Me and @waquidvp  fixed some of them, we are waiting for new textInput pull request to be merged to work on it, also I have some questions about searchBar styling for RTL

**Comment by iyadthayyil** [comment]
@satya164 I have fixed RTL support of icons as you requested, but some tests are failing can you take a look on it please.

**Comment by satya164** [comment]
@iyadthayyil awesome. to update the snapshot tests you can run `yarn test -u` and to fix the eslint errors, you can run `yarn lint --fix`

**Comment by ferrannp** [comment]
It looks like we still have some Flow errors.

**Comment by defint** [comment]
Hello! 
First of all we are very happy to use your library, it's cool, well documented and really reduces amount of our headache. We are currently in the process of development one production application and recently we ran into one problem with arabic language support for input fields.

We know that you are in the process of fixing it, but due to our time constraints  it's really important for us to know at least approximate schedule for fixing this problem. So we can make a decision whether it would be better just to wait for your fixes, or to fork and try to support it on our own. So, could you please give us approximate amount of time you are planning to spend on fixes, if it wouldn't bother you much?

Looking forward for your answers and thank you for your work.

Regards, 
Avalanche Laboratory developers

**Comment by satya164** [comment]
@defint Hey, we can't provide a timeline yet. I'd suggest forking it for now and maybe send a pull request :D

Also, it'll better if you wait till #429 is merged before you fork :)

**Comment by ferrannp** [comment]
@iyadthayyil do you need any help to land this?

**Comment by iyadthayyil** [comment]
I have no idea about the errors, @satya164 @ferrannp your help is highly appreciated.

**Comment by hsam1997** [comment]
after all these changes how we can make lists RTL ?

**Comment by Masoud-MSK** [comment]
Does _TextInput_ support RTL?

**Comment by Trancever** [comment]
@Masoud-MSK Yes, it does

**Comment by mtn1988** [comment]
After updating React Native from **0.58.6** to **0.59.4**, TextInput doesn't support RTL anymore!!
My react-native-paper version is 2.15.2

**Comment by meliodev** [comment]
RTL is not working for TextInput. I tested on Android.

**Pull request closed without merging**
