### PR TITLE
Fix TouchableRipple throwing because of `setNativeProps`

### PR DESCRIPTION
**Pull request by ahmedlhanafy**
This fixes https://github.com/callstack/react-native-paper/issues/157

### CODE REVIEW

**Comment by satya164** [comment]
I'm not sure this is the proper fix. This changes the behaviour on iOS by wrapping the child in an additional View, which means that if you want to have different styling, say stretch the element to full screen with `flex: 1`, it won't work.

**Comment by ahmedlhanafy** [comment]
@satya164 Hmmm 🤔 So what do you propose?

**Comment by satya164** [comment]
Dunno. I'll take a look.

**Comment by lukewalczak** [comment]
We can wrap icon in view. https://github.com/callstack/react-native-paper/pull/163

**Pull request closed without merging**
