### PR TITLE
Add disabled props

### PR DESCRIPTION
**Pull request by bosung90**

### CODE REVIEW

**Comment by ferrannp** [comment]
@bosung90 is there a reason to have a FAB disabled? Have you found this in material guideliness?

**Comment by bosung90** [comment]
@ferrannp Yes, I use this FAB button as "confirm purchase" button. I need to disable this button while server confirms that the payment has been successfully processed. I didn't check the material guidelines but it is a button, so I don't see a reason why disabled props should not be passed through?

**Comment by jaulz** [comment]
@bosung90 do you need help?

**Comment by bosung90** [comment]
@jaulz Thanks! I am actually really busy this week. I was thinking of working on it next weekend but if you can help it would be wonderful. I just found out that the text component in line 109 also needs 
`pointerEvents="none"` because the text will block the touch events underneath. Thanks!

**Comment by jaulz** [comment]
Since I could not push to your repository please see this PR: https://github.com/callstack/react-native-paper/pull/445

**Comment by ferrannp** [comment]
Close in favour of #445.

**Pull request closed without merging**
