### PR TITLE
Update DataTableCell.tsx to include number of lines

### PR DESCRIPTION
**Pull request by kejal280792**

### CODE REVIEW

**Comment by Trancever** [comment]
@kejal280792 Hi, thanks for PR. Could you post a screenshot? Also make sure eslint is passing.

**Comment by Trancever** [comment]
@kejal280792 Screenshot of table. We would like to see how it looks like.

**Comment by bjackson** [comment]
Would you be open to reopening this PR?

Here's an example where `numberOfLines=1`:
image

Here's an example where `numberOfLines=8`:
image

**Comment by avantassel** [comment]
What ever happened to this?

**Comment by Surangaup** [comment]
You have to code look like this. setting the **numberOfLines prop** is not enough. 

```
   <DataTable.Title key='totalDays' numberOfLines={2} >
          <View>
            <Text>Line 1</Text>
            <Text>Line 2</Text>
          </View>
        </DataTable.Title>
```
Thank you documentation for wasting my time.

**Comment by ycjcl868** [comment]
What's the progress?

**Comment by sidnetopia** [comment]
Hi, can you reopen this?

**Pull request closed without merging**
