### PR TITLE
docs: fix wrong import in example

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

`StyleSheet`must be imported from `react-native`itself.

### Test plan

n/a

### CODE REVIEW

**Comment by Trancever** [comment]
Hi @jaulz ! Thanks for this PR. Could you change merge branch to master?

**Comment by jaulz** [comment]
Sorry, let me rebase in a second...

**Comment by Trancever** [comment]
@jaulz If you have any troubles with changing branch, you can create another PR and close this one. It's gonna be fine :)

**Comment by jaulz** [comment]
@Trancever now we got it I think :-)

**Pull request merged**
