### PR TITLE
fix: fixes #2439 remove cycles

### LINKED ISSUE #2439: Require cycle warnings is still appear after upgrade to 4.5.0
### Screenshots (if applicable)

image

### What have you tried

```bash
rm -rf node_modules
npm install
npm start -- --reset-cache
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.63.3
| react-native-paper    | 4.5.0
| node                  | 14.5.0
| npm or yarn           | npm
| expo sdk              | bare workflow

### PR DESCRIPTION
**Pull request by maltoze**
### Summary

#2439  #639
#1851 https://github.com/callstack/react-native-paper/pull/2378#issuecomment-746290443

### CODE REVIEW

**Comment by Trancever** [comment]
@maltoze This change breaks our babel plugin so it's very unlikely we will merge it, but do you still have warnings on the latest version?

**Comment by maltoze** [comment]
@Trancever Yes, warnings still here.

**Comment by kamalkemo** [comment]
@Trancever .. yes warnings with latest version
image

**Comment by raajnadar** [comment]
Make sure you cleared the metro cache

**Comment by kamalkemo** [comment]
@raajnadar .. I get the error on a new machine where I never installed older versions of react-native-paper

**Comment by allexwentworthok** [comment]
this problem was solved?

**Comment by Trancever** [comment]
Closing this in favor of https://github.com/callstack/react-native-paper/pull/2463

**Pull request closed without merging**
