### PR TITLE
fix: change chip close icon to material community icon

### PR DESCRIPTION
**Pull request by RichardLindhout**
Current situation with v3 is the left but it needs to be the right icon like in v2 ;)

I can't fix the test because the only thing is see is a square in the snapshots.

Schermafbeelding 2019-08-21 om 14 39 33

### CODE REVIEW

**Comment by jaysbytes** [comment]
Hi @RichardLindhout. You can fix test using `yarn test -u`. It should update snapshots and then commit everything and push.

**Comment by RichardLindhout** [comment]
Mind=blown been doing all the snapshots updates myself last time xD

**Comment by RichardLindhout** [comment]
@jaysbytes Done, had some difficulties with squashing. Did it for the first time, but I think it should be fine now!

**Comment by jaysbytes** [comment]
@RichardLindhout 
> Mind=blown been doing all the snapshots updates myself last time xD
It happens :D But look, now you have a piece of new knowledge and also contribution.
Also, you don't have to worry about squashing, we will squash your commit anyway while merging a PR

**Pull request merged**
