### PR TITLE
[Test] Do not publish lib

### PR DESCRIPTION
**Pull request by Trancever**

### CODE REVIEW

**Comment by cpojer** [comment]
This is amazing, thanks for doing this <3

**Comment by Trancever** [comment]
@cpojer One gotcha. To use the babel plugin that we provide you'll probably have to use module resolver and resolve `react-native-paper` -> `react-native-paper-light`.

**Comment by cpojer** [comment]
I'm actually using it like this:

```
"react-native-paper": "npm:react-native-paper-light@^4.0.0-alpha.1",
```

**Comment by Trancever** [comment]
Ohh, so it should work out of the box. Let us know if you encounter any issues 👍

**Pull request closed without merging**
