### PR TITLE
feat: ContentStyle prop for Button

### PR DESCRIPTION
**Pull request by alexmbp**
### Motivation

Sometimes in project we need more customisation for component, that probably will make it not following guidelines. Full width buttons / custom height buttons - are good samples for it. So I've added extra prop to allow adding extra styles to buttons content.
Also I was thinking about height / fullWidth / fullSize prop. But think it will be overengineering.

### Test plan

I've added usage  example and also screenshot is here
[Examples Screenshot](https://user-images.githubusercontent.com/17987276/39042739-4226d1bc-4494-11e8-8841-696979ab0a25.jpeg)

### CODE REVIEW

**Comment by ferrannp** [comment]
What do you think @satya164 ?

**Comment by satya164** [comment]
Thanks for the PR.

We don't want to expose styles for internal implementation details. Is your issue solved by just adding `flex: 1` to `styles.content` by default?

**Comment by alexmbp** [comment]
Hello, @satya164 ! Well. It doesn't I still need to fix
justifyContent: 'center' <- to move spinner and label together.

Also, setting flex: 1 by default will break 'default' behaviour.

@ferrannp Hello! We have discussed TS/Flow a bit at React Native Camp.

**Comment by alexmbp** [comment]
Hey! Any suggestions here? Probably prop for height?

**Comment by satya164** [comment]
If you can figure out a way to make the touchable fill it's parent, we'd accept a PR for that.

**Comment by ferrannp** [comment]
Closing in favour of https://github.com/callstack/react-native-paper/pull/336.

**Pull request closed without merging**
