### PR TITLE
fix: custom size icon for BottomNavigation #1926 & #455

### PR DESCRIPTION
**Pull request by kilicfurkan**
### Summary

BottomNavigation's label icon size was default 24 px. In issue #1926 & #455, people want to change icon size. So, I added `iconSize` parameter to BottomNavigation in order to change icon size dynamically but still, the icon's default size is 24 px.

### Test plan

You can give `iconSize` parameter to BottomNavigation in order to test it.

**24px icon:** Simulator Screen Shot - iPhone 11 - 2020-06-14 at 13 25 28

**36px icon:** Simulator Screen Shot - iPhone 11 - 2020-06-14 at 13 25 57

### CODE REVIEW

**Comment by KristenLeach** [comment]
This is EXACTLY what I need. I would love to see this merged soon!

**Comment by Trancever** [comment]
@kilicfurkan Sorry for a long delay with the review. Could you recreate the PR? We replaced master branch with a 4.0 in the meantime and the history is a broken now :/

**Comment by kilicfurkan** [comment]
@Trancever  no problem. I will open it again as soon as possible.

**Comment by kilicfurkan** [comment]
@Trancever, @KristenLeach I created a new pull request (#2197).

**Pull request closed without merging**
