### PR TITLE
fix: textAlignVertical not passing down for TextInput

### PR DESCRIPTION
**Pull request by Huxpro**
### Motivation

Tentatively fix https://github.com/callstack/react-native-paper/issues/1570 and improve #1820 

### Test plan

See updated examples on TextInput

### CODE REVIEW

**Comment by zoolyka** [comment]
Any chance that this will go live some day? Thanks.

**Comment by CaffeinatedFunctionality** [comment]
Why is this still not resolved? I kinda need it

**Comment by Huxpro** [comment]
Hey @grabbou, (since you've the only once in the callstack i've been in contact), do you know is this PR not getting reviewed for sooooo long and now closed due to staleness? Thanks!

**Comment by rajaravivarman** [comment]
Hi, Dec 2020 and still this issue exists in TextInput.

**Comment by franbe7** [comment]
Hi, still this issue happening in May 2021.
Could you open this PR again and try to resolve it? It would be great. Thanks!

**Comment by alex-i0** [comment]
Unfortunately @franbe7 is right, it currently doesn't work. Setting vertical align for TextInput is a basic thing, but very needed.

**Comment by nikolaytsigvintsev** [comment]
Hi guys! 

Had to apply 'react-native-floating-labels'. 
Maybe it will help someone. 

Only need to add in file /node_modules/react-native-floating-label/index: 
'useNativeDriver: false,' in function animate(dirty) {...}

AND comment out

var styles = StyleSheet.create({
  element: {
    position: 'relative'
  },
  input: {
    // height: 40, <— comment out
....

export const Edit = () => {
  const [text, setText] = useState("");
  const [h, setHeight] = useState(0);

  const onLayout = (event) => {
    const { x, y, width, height } = event.nativeEvent.layout;
    setHeight(height);
  };

  return (
    <KeyboardAvoidingView
      enabled
      behavior="padding"
      keyboardVerticalOffset={70}
      style={{ flex: 1 }}
    >
      <SafeAreaView
        style={{ flex: 1, backgroundColor: "white" }}
        onLayout={onLayout}
      >
        <FloatingLabel
          value={text}
          labelStyle={{
            marginTop: 20,
            color: "grey",
            fontFamily: "System",
            fontSize: 16,
          }}
          inputStyle={{
            borderWidth: 0,
            marginTop: 30,
            marginLeft: 10,
            marginRight: 10,
            height: h,
          }}
          multiline
          editable
          onChangeText={(value) => setText(value)}
        >
          LABEL
        </FloatingLabel>
      </SafeAreaView>
    </KeyboardAvoidingView>
  );
});

**Pull request closed without merging**
