### PR TITLE
feat: added prop to override fontSize

### PR DESCRIPTION
**Pull request by netbull**
Possibility to set the fontSize when "string" is passed as child.

### CODE REVIEW

**Comment by jaysbytes** [comment]
Thank you for the PR but unfortunately, this prop is too specific. In the future, someone would like to have bolded text, different font size, different font family etc. Adding `labelStyle` prop would be a better approach. See related issue #1273 .

**Comment by netbull** [comment]
@jaysbytes Thanks! That's a valid point. :)

**Comment by pan-pawel** [comment]
@netbull I added PR with labelStyle for button. I will notify you if we add it to paper

**Comment by pan-pawel** [comment]
@netbull we added labelStyle to master, so with next release you will be able to set custom font for button

**Comment by netbull** [comment]
@pan-pawel that's great! thanks :)

**Pull request closed without merging**
