### PR TITLE
feat(ProgressBar): add `progressBarStyle`

### PR DESCRIPTION
**Pull request by jamesbechet**
Add the `progressBarStyle` prop to update the progress bar's style.

### Motivation
I couldn't find a way to change the progress bar's height.

### Test plan
N/A

### CODE REVIEW

**Comment by Trancever** [comment]
@jamesbechet Just pass `height` via `style` prop

**Comment by jamesbechet** [comment]
@Trancever that's the fist thing I tried and it only makes the container's bigger not the actual progress bar. See screenshots below:

Screen Shot 2019-10-17 at 11 06 29 AM
Screen Shot 2019-10-17 at 11 05 58 AM
Screen Shot 2019-10-17 at 11 08 20 AM

**Comment by Trancever** [comment]
Which version of paper do you use? 2.x or 3.x ?

**Comment by jamesbechet** [comment]
@Trancever latest available in npm `2.16.0`

**Comment by Trancever** [comment]
Ohh, right. In v2 we do not support it. It works on in 3.0-alpha./ We are gonna release stable 3.0 tomorrow.

**Comment by jamesbechet** [comment]
@Trancever still doesn't work in `3.0.0`

Screen Shot 2019-10-23 at 6 08 34 PM
Screen Shot 2019-10-23 at 6 08 46 PM
Screen Shot 2019-10-23 at 6 09 08 PM

**Pull request closed without merging**
