### PR TITLE
[WIP] docs: ✨ Dark mode 🌚

### PR DESCRIPTION
**Pull request by petrleocompel**
No more burned eyes

Needs callstack/component-docs#31

### Motivation

Developing in night is hard and flashing white screen of docs is not really good. 

### Test plan

Needs review docs if are OK.

Screenshot 2020-02-21 at 00 28 57

### CODE REVIEW

**Comment by petrleocompel** [comment]
Found out i modified some files accidentaly. (spaces and enters) i will remove that today.

**Comment by petrleocompel** [comment]
Removed unwated changes from commit. (spaces and enters - lines which I did not chage)
(🤔 maybe those files should be reformated)

Waiting for callstack/component-docs#31

**Comment by Trancever** [comment]
@petrleocompel Your PR in component docs is merged and we already released version 0.21. Could you make the necessary changes in this PR so we can merge it?

**Comment by petrleocompel** [comment]
@Trancever finally. 
Yes i will look on that. eta 3 days.

**Comment by jbinda** [comment]
@Trancever I have synced the PR with master branch so I believe it is in good shape to merge

**Comment by Trancever** [comment]
Awesome work folks!

**Pull request merged**
