### PR TITLE
docs: Add imports to doc examples - closes #223

### LINKED ISSUE #223: Add imports to docs examples
Currently docs feature examples like this:
```js
const MyComponent = () => (
  <Button raised onPress={() => console.log('Pressed')}>
    Press me
  </Button>
);
```
What I find not great for DX here is the lack of `import` statement, which clearly states how to import the module.

This looks much better and removes the ambiguity of how to import specific component:
```js
import { Button } from 'react-native-paper';

const MyComponent = () => (
  <Button raised onPress={() => console.log('Pressed')}>
    Press me
  </Button>
);
```

### PR DESCRIPTION
**Pull request by iamclaytonray**
### Motivation

Adds imports to docs for better DX.

### Extra Note:

I know that some of the docs are missing altogether. I thought maybe that could be done in a separate PR? I can add to this one if you'd like those finished up. Just let me know!

### CODE REVIEW

**Comment by iamclaytonray** [comment]
I know that some of the docs are missing altogether. I thought maybe that could be done in a separate PR? I can add to this one if you'd like those finished up. Just let me know!

**Comment by iamclaytonray** [comment]
Sounds good. Will try to get this done tonight if I get the time. Thanks!

**Comment by iamclaytonray** [comment]
@satya164 - Do you have any thoughts on my last sentence in my initial comment?

> I know that some of the docs are missing altogether. I thought maybe that could be done in a separate PR? I can add to this one if you'd like those finished up. Just let me know!

**Comment by satya164** [comment]
> I know that some of the docs are missing altogether. I thought maybe that could be done in a separate PR

Do you mean that some of the components are missing examples? Yes, separate PR is good.

**Comment by iamclaytonray** [comment]
Yeah. I'll write docs on them as soon as I get a break from work. Just got slammed with a lot of stuff so I may not be able to do the rest of the docs

**Pull request merged**
