### PR TITLE
docs: minor layout updates on the new docs

### PR DESCRIPTION
**Pull request by yamankatby**
### Summary
I was taking a look to the docs branch and I've drafted the following minor changes: 

- Add the autogenerated index page to the components category

  https://user-images.githubusercontent.com/35961879/214847427-62815ebd-ba47-4f42-b98d-5a39c78c930b.mov

- Apply react-native-paper brand colors to the docs

  brand colors

- Make some tweaks to the Navbar

  Navbar tweaks

I did them all in one branch as they are all small changes, however, have a look at the commits titles, they accurately describe the changes

### CODE REVIEW

**Comment by lukewalczak** [comment]
Hey @yamankatby, this is the latest [PR](https://github.com/callstack/react-native-paper/pull/3614) related to the docs migration to Docusaurus, so please target the branch called `docs/next` – we treat that branch as a feature branch related to the docs.

**Comment by yamankatby** [comment]
Hey @lukewalczak, thanks for the heads up 🙏
Now this PR is targeting `docs/next`

**Comment by yamankatby** [comment]
Some more tweaks to navbar's community links
nav community links

**Review by Drakeoon — APPROVED** [review]

**Review by lukewalczak — APPROVED** [review]
Thanks @yamankatby 🚀

**Pull request merged**
