### PR TITLE
Don't add a setTimeout if Infinity is passed as duration

### LINKED ISSUE #878: Snackbar Duration Question
I assumed any number value could be passed to the duration prop. Is this not the case?

### Current behaviour

Passing Infinity to the duration prop gives me an error:

Expected dynamic type 'double' but had type 'null'. (constructing arguments for Timing.createTimer at argument index 1)

### Expected behaviour

Assumed we could pass any value that is a number to the duration prop.

### Code sample

```
        <Snackbar
          visible={this.props.isBLESnackbarVisible}
          onDismiss={this.onDismiss}
          duration={Infinity}
          theme={theme}
          action={{
            label: 'SETTINGS',
            onPress: () => {
              AndroidOpenSettings.bluetoothSettings();
            },
          }}
        >
          Try resetting bluetooth.
        </Snackbar>
```

### What have you tried

I have passed in other number values with success (i.e. 15000, 30000, etc.)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android
| react-native          | 0.57.8
| react-native-paper    | 2.7.0
| node                  | 7.0.0
| npm or yarn           | 6.4.1

### PR DESCRIPTION
**Pull request by Taym95**
Try to fix #878

### CODE REVIEW

**Comment by Trancever** [comment]
Hey, Thanks for PR. I didn't see your comment and also created PR for that :D. Could you changeyour PR to be like mine https://github.com/callstack/react-native-paper/pull/902 ? Once it's done, we will merge yours :)

**Comment by Taym95** [comment]
Thank you 🤗!

**Comment by Trancever** [comment]
One more thing, lint is not passing. Could you make it passing? Run locally `npm lint` or `yarn lint` and you'll see the error :)

**Comment by Taym95** [comment]
Weird should not allow commit, fixed!

**Comment by Trancever** [comment]
Thanks!

**Pull request merged**
