### PR TITLE
feat: support loading indicator to Searchbar

### PR DESCRIPTION
**Pull request by brunohkbx**
### Motivation
It would be nice to be able to display a loading indicator when searching

ezgif com-video-to-gif

### Test plan
1. Download this branch
2. Open the Searchbar example
3. See the example using the loading indicator.

### CODE REVIEW

**Comment by Trancever** [comment]
@brunohkbx Why do you hide close icon in "loading" state? Did you find it in the guidelines? Can you point me to the reference?

**Comment by brunohkbx** [comment]
@Trancever I hid the close icon to show up the loading indicator. 
There isn't any mention of that on MD guidelines and I don't think there's any about the button loading indicator either.
I've just thought it would be a nice addition.

**Comment by Trancever** [comment]
@brunohkbx We are not sure if replacing close icon with loading icon is the correct solution. The UX is not that great and MD Guideline does not mention it anywhere.

**Comment by satya164** [comment]
Yea, user should be able to delete the text when loading results.

**Comment by Trancever** [comment]
Closing this because the user can't delete text when the loading icon is shown. Feel free to submit a new PR if you come up with a solution to the mentioned problem.

**Pull request closed without merging**
