### PR TITLE
feat: smooth icon change in `IconButton`

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

Whenever the icon of `IconButton` changes, the change looks quite hard. This change will introduce the same effect as in `FAB`s.

### Test plan

n/a

### CODE REVIEW

**Comment by ferrannp** [comment]
@jaulz can you give an example of use case for this? Some gifs maybe?

**Comment by jaulz** [comment]
@ferrannp I am not able to create a gif right now but my use case is that I want to change the icon of an `Appbar.Action` button depending on whether items are selected or not. I could of course render a different component but that transition looks hard and not really appealing. If we use `CrossFadeIcon` instead the change would look nice and smooth and it would not change the API.

**Comment by ferrannp** [comment]
Oh I see. Will check. I know this is the use case for the Contextual Action Bar on Android. Would be nice to have this on Paper.

**Comment by Trancever** [comment]
@jaulz Can you upload a gif showing transition? I still see it quite sharp, just the transition is a bit delayed.

**Comment by jaulz** [comment]
@ferrannp yep, that's basically my use case
@Trancever I don't have a gif right now but the animation is the same as in `FAB`s (which are the reason why the `CrossFadeIcon` was introduced I assume)

**Comment by Trancever** [comment]
@jaulz So I figured out that there is something wrong with my device and animation is not shown.. but it works fine on other devices :)

**Pull request merged**
