### PR TITLE
fix: adjust gestures distance for iOS on example app

### LINKED ISSUE #282: Swipe from left edge opens side menu in iOS
Using the example app in Expo.

### Current behaviour

Swiping from the left edge of the screen opens the side menu.

### Expected behaviour

As per the standard iOS user experience, the app should navigate back to the previous screen in the stack.  

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 11

### PR DESCRIPTION
**Pull request by luissmg**
### Motivation

Fixes #282 in example app. It gives extra space for gestures in `react-navigation`.

### Test plan

Open the example app, change screen and test the gestures in iOS.

### CODE REVIEW

**Comment by satya164** [comment]
Oops. Sorry for the conflicts :(

The file was renamed to `RootNavigator.native.js`. Can you update the PR?

**Comment by luissmg** [comment]
Ye sure, will do it today

**Comment by luissmg** [comment]
I will close this one, create a new one and reference this.

**Comment by satya164** [comment]
@all-contributors lets add luissmg for code

**Comment by luissmg** [comment]
Thanks!!!

**Pull request closed without merging**
