### PR TITLE
editable and disabled is different

### PR DESCRIPTION
**Pull request by sm2017**
https://github.com/callstack/react-native-paper/pull/866#issuecomment-473229503

### CODE REVIEW

**Comment by ferrannp** [comment]
Duplicated.

**Comment by Trancever** [comment]
@sm2017 Is there any chance you could resolve conflicts? After that, we will merge it.

**Comment by sm2017** [comment]
@Trancever Sorry I have no free time now

**Comment by jbinda** [comment]
I made #1069 which also includes fix for #986 and #737

**Pull request closed without merging**
