### PR TITLE
fix: export gestureResponderEvent to add preventDefault support on web

### PR DESCRIPTION
**Pull request by RichardLindhout**
### Summary
I need this to add event.preventDefault on web version of button.
(a I do a href links and need to prevent default behaviour of link but also support SEO + ctrl+click.

### Test plan

Running tests

### CODE REVIEW

**Comment by RichardLindhout** [comment]
Also closes https://github.com/callstack/react-native-paper/pull/3410

**Comment by RichardLindhout** [comment]
Will solve conflicts

**Comment by RichardLindhout** [comment]
@lukewalczak ready :)

**Comment by lukewalczak** [comment]
Thanks @RichardLindhout for help! Most probably on Monday, I will check your changes

**Review by lukewalczak — APPROVED** [review]
Thanks @RichardLindhout

**Comment by lukewalczak** [comment]
Hey @RichardLindhout, please rebase your PR with `main`, since there are some conflicts.

**Comment by RichardLindhout** [comment]
@lukewalczak done!

**Pull request merged**
