### PR TITLE
feat: export icon (#1694)

### PR DESCRIPTION
**Pull request by StheffanyHadlich**
### Motivation

This PR solves #1694, exporting `Icon` component in order to allow users to customize react-native-paper components.

Please let me know about any necessary changes

### CODE REVIEW

**Comment by satya164** [comment]
Why wouldn't you use `MaterialCommunityIcons` or whatever icon you want directly?

**Comment by Trancever** [comment]
Please use Vector Icon directly. paper's Icon is an internal component that we don't want to expose.

**Comment by RichardLindhout** [comment]
@satya164 @Trancever This can be actually difficult sometimes e.g. I'm now building a tabs component for react-native-paper and I would want the react-native-paper abstraction since it has already things inside of it like the render function e.t.c. expo/web abstractions.

If I go with the MaterialCommunityIcons directly it would not work with expo

**Comment by RichardLindhout** [comment]
Actually it's less hard now since __expo dependency has dropped. Sorry for bothering ;)

**Pull request closed without merging**
