### PR TITLE
fix: add ref typings

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

This PR will add the remaining missing refs typings. Please let me know if anything is missing.

### Test plan

Pass ref to components and no typing issue should occur.

### CODE REVIEW

**Comment by jaulz** [comment]
See related issue: https://github.com/callstack/react-native-paper/issues/1692

**Comment by Trancever** [comment]
@jaulz Typescript check is failing on CI. Would you mind taking a look at it?

**Comment by jaulz** [comment]
@Trancever here we go 😊

**Comment by Trancever** [comment]
Thanks!

**Pull request merged**
