### PR TITLE
BREAKING: TextInput redesign

### LINKED ISSUE #359: TextInput: Redesign
- [ ] Background color for input container with border radius
- [ ] Add outlines text fields
- [ ] Support a leading icon
- [ ] Support a trailing icon (e.g. error, clear)

image

https://material.io/design/components/text-fields.html#spec

### PR DESCRIPTION
**Pull request by gawrysiak**
TextInput redesign - work in progress

So far:

screen shot 2018-06-21 at 23 25 13

[TODO](https://github.com/callstack/react-native-paper/pull/429/files#diff-668f4dd23f3a0a24c50d7c852c1fa633R301)

Fixes #359.

### CODE REVIEW

**Comment by turtlegood** [comment]
Hello

**Comment by gawrysiak** [comment]
@turtlegood hey, it's still missing the leading & trailing icon features and some polishing. I'll try to figure it out through the weekend

**Comment by turtlegood** [comment]
@gawrysiak wow thanks!

**Comment by gawrysiak** [comment]
@satya164 this one wasn't so easy for me with all the features included and my first try on animations. Took ages, sometimes feels hacky, I'm also unsure about some of the behaviours (like outlined + leading icon). Please review carefully

**Comment by henrymoulton** [comment]
Hey guys just want to say I'm a big fan of React Native Paper... any update when this planning on being merged?

**Comment by gawrysiak** [comment]
Hi @henrymoulton 
There's not so much left to complete 2.0. You should be able to see the details [here](https://github.com/callstack/react-native-paper/milestone/2) and the RTL task was recently merged. Also, @ferrannp will be soon introducing Paper 2.0 at [React Native EU](https://www.facebook.com/reactnativeeu/posts/419087118579006) which makes it not so much time left to finish it. While it might be not so possible to give a date on particular tasks, React Native EU is less than 4 weeks away. Hope this works for you.

**Comment by henrymoulton** [comment]
@gawrysiak thanks Grzegorz for this and looking forward to the release 💯

**Comment by satya164** [comment]
I'm reviewing it. There are visual issues on Android, so it'll take some changes before merging.

**Comment by satya164** [comment]
Closing in favor of #522

**Pull request closed without merging**
