### PR TITLE
feat: support for maxFontSizeMultiplier in text component

### PR DESCRIPTION
**Pull request by lukewalczak**
### Summary

- [x] - add prop descriptions
- [x] - update snapshots
~~- [x] - add default values~~

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
> ### Summary
> * [x]  - add prop descriptions
> * [x]  - update snapshots
> * [x]  - add default values
> 
> ### Test plan

@lukewalczak There are two other components that need this I believe. I've recorded them https://github.com/callstack/react-native-paper/discussions/3905#discussioncomment-6037762.

**Comment by iM-GeeKy** [comment]
Is this planning to be released in `5.11.0`? I'm currently using `patch-package` but have to manually apply these updates from version to version which is becoming an annoyance.

**Comment by iM-GeeKy** [comment]
> > ### Summary
> > 
> > * [x]   - add prop descriptions
> > * [x]   - update snapshots
> > * [x]   - add default values
> > 
> > ### Test plan
> 
> @lukewalczak There are two other components (`Searchbar.tsx` and `Dialog.Title`) that need this I believe. I've recorded them [#3905 (comment)](https://github.com/callstack/react-native-paper/discussions/3905#discussioncomment-6037762).

@lukewalczak Is there any particular reason this isn't being finished?

**Comment by lukewalczak** [comment]
Hello @iM-GeeKy,I intended to check another aspect concerning that feature, but unfortunately, I forgot about it, which has resulted in a delay in delivering those changes.

**Comment by iM-GeeKy** [comment]
> Hello @iM-GeeKy,I intended to check another aspect concerning that feature, but unfortunately, I forgot about it, which has resulted in a delay in delivering those changes.

Sounds good, I've been using these changes with the two other components (Searchbar.tsx and Dialog.Title) via `patch-package` for a while and it has seemed to be working which is the only reason why I was interested in the delay, but thank you!

**Comment by lukewalczak** [comment]
Edit: I've removed the initially added default value for `maxFontSizeMultiplier` prop.

@iM-GeeKy According to the both `SearchBar` and `Dialog.Title` components, looks like those are supporting `maxFontSizeMultiplier` due to spreading `rest` props into core components – respectively `TextInput` and `Text`.

**Comment by jacquesdev** [comment]
I just came looking for support on the button component, and so happy that the support for it is so close now! Thanks everyone for working on this!

**Pull request merged**
