### PR TITLE
fix: add support for changing the surface mode in the menu

### PR DESCRIPTION
**Pull request by lenzi-erickson**
### Motivation

I prefer the "flat" design approach on my components, and would like to be able to use the `Menu` component in flat mode.

### Related issue

You cannot currently change the `mode` on the `Surface` that is used in the `Menu` component.

### Test plan

Pull up the menu example and pass `mode="flat"` to one of the menus to test.

### CODE REVIEW

**Comment by seb-zabielski** [comment]
Hey,
Modal component has an “elevation” property. If you set `elevation={0}` it should look like a flat component. Does your change have a better/different effect than the elevation prop? 
https://callstack.github.io/react-native-paper/docs/components/Menu/#elevation

**Comment by lenzi-erickson** [comment]
> Hey, Modal component has an “elevation” property. If you set `elevation={0}` it should look like a flat component. Does your change have a better/different effect than the elevation prop? https://callstack.github.io/react-native-paper/docs/components/Menu/#elevation

`elevation={0}` does not do what I was wanting. In my opinion, it makes the menu look broken. If you run the example in this branch, you can see the differences.

Default
Screenshot 2024-06-19 at 2 23 44 PM

`elevation={0}`
Screenshot 2024-06-19 at 2 25 46 PM

`mode="flat"`
Screenshot 2024-06-19 at 2 27 07 PM

**Comment by seb-zabielski** [comment]
Now I see your point. Change looks good to me. Can you add a test to this case?

**Comment by lenzi-erickson** [comment]
> Now I see your point. Change looks good to me. Can you add a test to this case?

What are you wanting me to test, exactly? Since I'm just passing a prop through, and did not add any logic, I'm not sure what you are wanting me to test.

**Comment by lenzi-erickson** [comment]
I attempted to add some tests. If it's not what you are hoping for, I need some help getting it here, please.

**Comment by seb-zabielski** [comment]
This is exactly what I was expecting. Thanks!

**Review by seb-zabielski — APPROVED** [review]

**Comment by lenzi-erickson** [comment]
@seb-zabielski What else do I need to do to get this merged? And any ETA on the next release? I would love to get this in. Thanks!

**Pull request merged**
