### PR TITLE
refactor(docs): replace component-docs with docusaurus

### PR DESCRIPTION
**Pull request by andriytsaryov**
### Summary

This PR replaces [component-docs](https://github.com/callstack/component-docs) with [docusaurus](https://github.com/facebook/docusaurus) for documentation since other modern OSS projects are using it.

### Test plan

1. `cd docusaurus/`
2. `yarn build`
3. `yarn serve`

### Todo

- [x] Initialize new docs site (using [docusaurus](https://github.com/facebook/docusaurus))
- [x] Write custom plugin that utilizes component-docs’s [parser](https://github.com/callstack/component-docs/blob/master/src/parsers/component.tsx) to parse components' description and props (using this approach we won't need to do any changes to existing components docs)
- [x] Fix: components categories structure does not match previous docs version
- [x] Fix: icons preview on the Icons page
- [x] Fix: component props table (better styling and references support like in the previous docs version)
- [x] Configure homepage
- [x] Initial review and feedback
- [x] [Feedback] Dark/light mode for the home page
- [x] [Feedback] Top navigation changes
- [x] [Feedback] Add search
- [x] [Feedback] Refactor component-docs-plugin so it will generate correct docs structure/navigation
- [x] [Feedback] Refactor PropTable component to support different annotations
- [x] Review
- [x] Actualize guides pages with the latest changes
- [x] Update internal links the docs/pages
- [ ] Complete [Algolia search](https://docusaurus.io/docs/search#using-algolia-docsearch) setup (@lukewalczak has requested API keys)
- [ ] Rebase branch (apply changes to the guides pages only)
- [ ] Remove old docs site (using [component-docs](https://github.com/callstack/component-docs)) (it might be done as the latest step to reduce the potential merge conflicts)

### CODE REVIEW

**Comment by flexbox** [comment]
This is nice!

> Get the new site reviewed
@andriytsaryov let me know if you want some feedback / stress tests :)

**Comment by lukewalczak** [comment]
Hey @flexbox, since that PR is still in the draft shape, please let the author finish the work and maybe I will ping you once it's ready for review, wdyt?

**Comment by flexbox** [comment]
@lukewalczak Indeed, it makes sense.

@andriytsaryov 
No rush at all! I didn't want you to feel pressure, just sending good vibes and support for your work 🙂

**Comment by andriytsaryov** [comment]
@lukewalczak @flexbox, I have pushed several improvements and fixes and I think I reached the point when it would be great to get this PR reviewed. I would not actialize docs with latest changes until the PR is pre-finalized.

**Comment by lukewalczak** [comment]
@andriytsaryov awesome work so far! I'm really happy to see the docs adjusted to docusaurus 🔥 it looks solid 💪🏽 
Below I've left a couple of requests which we can discuss or directly address if possible ✌🏽 

- [ ] - use screenshots for dark theme, when that mode is set. Prolly you can use `useColorMode` from `@docusaurus/theme-common` and then apply dark screenshots equivalent
- [ ] - adjust props in `navigationState` in `BottomNavigation` component
- [ ] - when v5 was introduced, some components (`DialogIcon`) or props (e.g. `sceneAnimationType` in `BottomNavigation`) received appropriate "badge annotation" (supported, renamed or deprecated) to inform users about the change (please check that [link](https://callstack.github.io/react-native-paper/bottom-navigation.html#navigationState) for the reference). 
Would be awesome to support it here as well – we can add something similar to the previous docs by adding a _badge_ component in `PropTable.tsx` file. Maybe you can adjust the code which I used for patching `components-docs`:

```js
const badge = description && ANNOTATION_BADGES.find((i) => i == description.split(' ')[0]);
const containsBadge = description && badge && description.startsWith(badge);
const badgeLine = containsBadge ? description.split('\n')[0] : null;
const badgeDescription = containsBadge && badgeLine ? badgeLine.replace(badge || '', '').trim() : null;
```

- [ ] - can we merge both tabs `Guides` and `Components` into one called `Docs` and shift it to the right. On the left side we can add `React Native Paper` with the logo. Basically, I would like to match the pattern from [RNTL](https://callstack.github.io/react-native-testing-library/) page.
- [ ] - are we able to rearrange screenshots e.g. in `FAB` or `Card` to be in the row?
- [ ] - in components which contain _subcomponents_ e.g. `Card`, `Appbar`, `Checkbox` can we have the **main** one opened by default (similar to the old docs)?
- [ ] - please remove redundant nesting `Button` docs:
image

**Comment by andriytsaryov** [comment]
@lukewalczak, I resolved all issues mentioned by you and simplified component docs generation process. Please review it one more time before I can proceed.

**Comment by andriytsaryov** [comment]
Added fixes for

- [x] Search (replaced `docusaurus-lunr-search` with `@easyops-cn/docusaurus-search-local`)
- [x] Migrate Guides/Showcase page
- [x] Display leading prop badge next to the prop name instead of description body
- [x] Display correct prop descriptions (e.g. for BottomNavigation/navigationState)

**Comment by Drakeoon** [comment]
Merging it to the feature branch for documentation to continue working there

**Pull request merged**
