### PR TITLE
[WIP] Bottom sheet

### LINKED ISSUE #2: Bottom sheets
[Material Design Docs Link](https://material.google.com/components/bottom-sheets.html#)

### PR DESCRIPTION
**Pull request by satya164**
image

- [ ] Persistent bottom sheet
- [ ] Icon grid for bottom sheet
- [ ] Make sure initial height does not extend beyond the 16:9 ratio
- [ ] Make sure it works well when content are more than screen height

Fixes #2

### CODE REVIEW

**Comment by ferrannp** [comment]
Closing to reopen with new Travis.

**Comment by ferrannp** [comment]
@satya164 requested for this issue to be closed.

**Comment by vko-online** [comment]
Why it's closed?

**Comment by vko-online** [comment]
@satya164 why its closed, berry useful component tho

**Pull request closed without merging**
