### PR TITLE
feat: Text Input type password + icon visible and visible_off

### PR DESCRIPTION
**Pull request by tonoli**
### Motivation

When the Text Input is a password there is no prop to declare it. 
I also added the visibility and visibility off icon when it is a password to respectively show and hide the password. 

https://material.io/design/components/text-fields.html#filled-text-field

### Test plan

```
<TextInput
            mode="flat"
            type="password"
            style={styles.inputContainerStyle}
            label="Password"
            value={this.state.password}
            onChangeText={password => this.setState({ password })}
 />
```

### CODE REVIEW

**Comment by ferrannp** [comment]
Related https://github.com/callstack/react-native-paper/pull/587.

**Comment by tonoli** [comment]
It's now exactly the same but sure we should definitely work on that feature together

**Comment by tonoli** [comment]
Any news about this? @Esemesek  @ferrannp

**Comment by peterchibunna** [comment]
For those in need of a password input, you can create your custom component.
```
import React from 'react';
import Icon from 'react-native-vector-icons/MaterialIcons';
import {View, StyleSheet} from 'react-native';
import {TextInput} from 'react-native-paper';

export default class PasswordInput extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			icEye: 'visibility-off',
			password: true
		}
	}

	changePwdType = () => {
		let newState;
		if (this.state.password) {
			newState = {
				icEye: 'visibility',
				password: false
			}
		} else {
			newState = {
				icEye: 'visibility-off',
				password: true
			}
		}

		// set new state value
		this.setState(newState)
	};


	render() {
		return (
			<View>
				<TextInput {...this.props} secureTextEntry={this.state.password}/>
				<Icon
					style={styles.icon}
					name={this.state.icEye}
					size={this.props.iconSize}
					color={this.props.iconColor}
					onPress={this.changePwdType}
				/>
			</View>
		);
	}
}


export const styles = StyleSheet.create({

	icon: {
		position: 'absolute',
		top: 20,
		right: 10
	}

});

PasswordInput.defaultProps = {
	iconSize: 25,
	label: 'Password',
};
```

You still have control over your custom component. Introducing this feature might attract other features we don't want to be dealing with at the moment.

**Comment by tonoli** [comment]
Hi guys! So I can close this PR, if I understood well you don't want to add this kind of prop to the Text input directly, but instead you need to create a custom component for it?

**Comment by tonoli** [comment]
I close the PR then! Thank you @peterchibunna for you code example! 

If I understood well you don't want to add this kind of prop to the Text input directly, but instead you need to create a custom component for it!

**Pull request closed without merging**
