### PR TITLE
docs: Add Groovy to Showcase

### PR DESCRIPTION
**Pull request by GabrielDierks**

### CODE REVIEW

**Comment by GabrielDierks** [comment]
@brunohkbx Would be nice to show my app is built with your awesome library! <3

**Comment by lukewalczak** [comment]
Hey @GabrielDierks, please fix the lint error.

**Comment by GabrielDierks** [comment]
@lukewalczak Done!

**Comment by lukewalczak** [comment]
Good job @GabrielDierks, thanks!

**Pull request merged**
