### PR TITLE
Remove StatusBar from FAB Group

### LINKED ISSUE #999: FAB Group auto change StatusBar barStyle when open
## Description

As the title, I can't find a way to persist the barStyle of my StatusBar, it auto turns light when the FAB.Group open.

## Screenshot

Screen Shot 2019-04-17 at 8 11 46 PM

Screen Shot 2019-04-17 at 8 11 43 PM

### PR DESCRIPTION
**Pull request by Taym95**
Fix #999

### CODE REVIEW

**Comment by Taym95** [comment]
Hey @satya164, I changed the base branch from master to 3.0.

**Comment by satya164** [comment]
We should also update the documentation mentioning how to use statusbar component along with it

**Comment by chadlavi-casebook** [comment]
I need this too, theming the FAB.Group with a white backdrop on iOS currently causes accessibility issues because the white status bar is hard-coded into the component.

**Comment by satya164** [comment]
> @chadlavi-casebook: looks like this is slated for the next major release... is it possible to get this as a bug fix on 2.X as well?

No. It's a breaking change

**Comment by chadlavi-casebook** [comment]
> No. It's a breaking change

Totally fair!

**Pull request merged**
