### PR TITLE
feat: allow configuring fontSize of TextInput label

### LINKED ISSUE #348: Changing fontSize of TextInput
TextInput Module fontSize doesn't get affected
### Current behaviour

fontSize remains 12 unaffected.

### Expected behaviour

fontSize should change right?? or am i missing something?

### Code sample

  <TextInput
        label='Email'
        value={this.state.text}
        onChangeText={text => this.setState({ text })}
       style={{flex:1, fontSize:16}}
      />

### Your Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.8.1
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B46
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: ^0.54.2 => 0.54.2

### PR DESCRIPTION
**Pull request by vieiralucas**
### Motivation
This PR aims to allow users to customize the fontSize of a `TextInput`'s label. Should FIX #348 

### Test plan

I added a TextInput to the example app showing this feature.

### Why this PR is Work In Progress?
I know this implementation has a problem because `react-native-paper` currently sends the `style` prop to a `View` component which is not supposed to receive `fontSize`.
So I don't know how to overcome this issue, do you have any suggestions?

Thanks ❤️

### CODE REVIEW

**Comment by satya164** [comment]
Hey! You can do something like `const { fontSize, ...rest } = StyleSheet.flatten(styles) || {}`

**Comment by satya164** [comment]
Yeah. Thanks! I'll check it soon.

**Comment by vieiralucas** [comment]
@satya164 Hello? Please let me know if there is anything that I can do to help you merge this.
Also anything else in the project that my contribution might be worth. ❤️

**Comment by satya164** [comment]
Sorry, haven't had time to take a look. Will do soon.

**Comment by vieiralucas** [comment]
Thanks, I'm sorry for bothering you. I'll just be more patient 😸

**Comment by thomasd25** [comment]
Any updates on this?

**Comment by satya164** [comment]
I ran this last week, but positioning of label is incorrect. I tried to fix it, but it wasn't very straightforward. It'll take time to fix and merge it unless someone sends a PR.

**Comment by vieiralucas** [comment]
@satya164 I think I fixed the positioning of label.

**Comment by satya164** [comment]
Thank you @vieiralucas! I'll check tomorrow

**Comment by vieiralucas** [comment]
Hey @Esemesek I'm not sure if my PR changes any `typings`.
It uses `fontSize` from `style` prop.
Am I missing something?

**Comment by Esemesek** [comment]
@vieiralucas You're right. I thought you've introduced to Prop to the component. My mistake 👍

**Comment by glenne** [comment]
This seems like a basic capability.  A quick search reveals a lot of others wanting this.  Please approve and merge.

**Comment by DAKZH** [comment]
:)

**Comment by Trancever** [comment]
@vieiralucas It looks like it's not working properly https://cdn.discordapp.com/attachments/438399234098855948/537552429085097984/Screenshot_20190123-094059.png

**Comment by Trancever** [comment]
@vieiralucas  It looks like it's not working properly, Tested only on Android

img

**Comment by ferrannp** [comment]
This is related to https://github.com/callstack/react-native-paper/issues/546.

Basically to support custom font size, all animations need to be calculated based on that so they are not broken. Do you plan to check into that @vieiralucas ?

**Comment by kkarkos** [comment]
fontSize still get's ignored in 2.16.0

**Comment by Trancever** [comment]
@kkarkos It's supported in alpha release of 3.0. We're going to release stable 3.0 in couple of days

**Pull request closed without merging**
