### PR TITLE
Migrate from Flow to TS

### PR DESCRIPTION
**Pull request by wojteg1337**
### Motivation
After upgrading Expo/RN version we faced over 700 flow issues, so we decided to migrate to TS

### Test plan

`yarn typescript` should pass

### CODE REVIEW

**Comment by raajnadar** [comment]
Should I update the CI config? In order to get green tick

**Comment by wojteg1337** [comment]
Sure - you can fix it, we can talk on discord in case of questions

**Comment by jaulz** [comment]
Great, work! 😊

**Comment by raajnadar** [comment]
Finally this will fix a lot of issue!

**Pull request merged**
