### PR TITLE
fix: use own ActivityIndicator in Button

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

So far the default `ActivityIndicator` from react-native was used but since we provide a custom one with Material Design we can use it in the button instead.

### Test plan

n/a

### CODE REVIEW

**Comment by ferrannp** [comment]
@jaulz can you fix conflicts?

**Comment by jaulz** [comment]
@ferrannp done but it seems that there is still something wrong with the snapshots in the 3.0 branch

**Comment by ferrannp** [comment]
@jaulz tests are passing for me in 3.0. Did you rebase that branch with yours? Or maybe just even open a new PR if there is too much trouble :)

**Comment by jaulz** [comment]
@ferrannp not sure what went wrong before but here we go ;)

**Comment by Trancever** [comment]
@jaulz The new one looks too big for me, check the screenshots.
58694223_1181057888730492_6411155231005999104_n

**Comment by Trancever** [comment]
@jaulz The new one looks too big for me, check the screenshots.
58694223_1181057888730492_6411155231005999104_n
58657563_597964124024372_9027658928455942144_n

**Comment by jaulz** [comment]
@Trancever should be better now 😊

**Pull request merged**
