### PR TITLE
feat: configure fonts more granuar

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

This PR allows to configure fonts more granular (i.e. currently, it let's you specify `fontWeight` but it can be extended). As mentioned by @satya164 in https://github.com/callstack/react-native-paper/issues/590 this will most likely land in 3.0.

### Test plan

See examples app.

### CODE REVIEW

**Comment by jaulz** [comment]
By the way, does it make sense to include `letter-spacing` as well in Typography? See https://material.io/design/typography/the-type-system.html#type-scale and https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/ which both specify such.

**Comment by satya164** [comment]
@jaulz yea why not

**Comment by RichardLindhout** [comment]
Excited for this feature ;)

**Comment by jaulz** [comment]
I just had a look at the letter spacing but since the spacing depends on the font and the size it makes it difficult to configure. The only way I could think of at the moment would be to define a letter spacing map in the theme, e.g.:
```
  ios: {
    regular: {
      fontFamily: 'System',
      fontWeight: '400',
      letterSpacing: {
        // See https://github.com/hectahertz/react-native-typography/blob/master/src/helpers/sanFranciscoSpacing.js
        6: 0.246,
        7: 0.223,
        8: 0.208,
        9: 0.171,
        10: 0.12,
        11: 0.06,
        12: 0,
      },
    },
  },
```

@satya164 what do you think?

**Comment by satya164** [comment]
My idea was that for fonts was that we'd be able to do `style={fonts.regular}`. I think if there is a letter spacing map inside, it'll get more complicated. The solution I can think of is that our `Text` component (or another component) accepts a prop to customize the letter spacing and adjusts it automatically based on font size. But I think let's leave it for now, we can come back to it later.

**Comment by jaulz** [comment]
Yep, that's what I thought as well. Though, in the future we could think about a `letterSpacing` function that takes the `fontFamily` and the `fontSize` as input parameters and calculates the letter spacing for predefined fonts - maybe even via the theme. Let's park it for now...

**Comment by geminiyellow** [comment]
good job, that is really what i want. 
i need to set a big font for old men.

**Comment by Trancever** [comment]
Hey @jaulz, Could you change target branch to 3.0?

**Comment by jaulz** [comment]
@Trancever done 😊 unfortunately, I don't have time to check for the conflicts right now.

**Comment by Trancever** [comment]
@jaulz No worries, take your time. Maybe someone from callstack will fix it in the meantime.

**Comment by jaulz** [comment]
@Trancever done

**Comment by jaulz** [comment]
@NoemiRozpara snapshots were still wrong but I'm sure you noticed it 😊 thanks for merging!

**Pull request merged**
