### PR TITLE
feat: Avatar component

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

Simple avatar component as mentioned in issue #531 

### Test plan

image

### CODE REVIEW

**Comment by satya164** [comment]
Maybe instead of `children`, `icon` and `image` props on a single `Avatar` component, maybe it'll be better to have `<Avatar.Text label="JH" />`, `<Avatar.Icon icon="folder" />` and `<Avatar.Image source={require('./user.png')} />`. Because otherwise it's not obvious what will happen when someone passes both `icon` and `image` etc.

**Comment by jaulz** [comment]
@satya164 thanks for the input. Can you please check again? 😊

**Comment by nahoc-petal** [comment]
Thank you! This looks really good.

**Comment by nahoc-petal** [comment]
Would it be possible to implement a border prop or elevation shadow?

**Comment by jaulz** [comment]
Should be possible via the style prop I guess. Or which props with which effect do you have in mind?

**Comment by nahoc-petal** [comment]
You're right, I didn't even think of the style prop. This has been a long day...

**Comment by BenWildeman** [comment]
> Maybe instead of `children`, `icon` and `image` props on a single `Avatar` component, maybe it'll be better to have `<Avatar.Text label="JH" />`, `<Avatar.Icon icon="folder" />` and `<Avatar.Image source={require('./user.png')} />`. Because otherwise it's not obvious what will happen when someone passes both `icon` and `image` etc.

I would argue that it would make sense that the avatar component should have a text prop as a fallback for when images don't render for whatever reason instead of this turning blank

**Comment by aqeelbe** [comment]
Please resolve the conflicts and  merge this feature . we need this feature in our app.

**Comment by jaulz** [comment]
@ferrannp I updated the types and now all checks passed 😊

**Comment by jaulz** [comment]
@ferrannp any updates on this?

**Comment by jaulz** [comment]
@Trancever please check now

**Comment by Trancever** [comment]
It looks good to me. @satya164 Could you take a look and check api?

**Comment by brunohkbx** [comment]
@satya164 could you please take a look?

**Comment by satya164** [comment]
Merged in b68fac70b0b77a1338ff80ed69e8c1cb293c6337

**Pull request closed without merging**
