### PR TITLE
chore: forward ref to `Button`

### LINKED ISSUE #3988: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
### Current behaviour

When using a Button, I get the following error.

```
import React from 'react';
import {Link} from 'expo-router';
import {Button} from 'react-native-paper';

export default function Page() {
  return (
    <Link href="/onboarding" asChild>
      <Button icon="camera" mode="contained">
        Go About
      </Button>
    </Link>
  );
}

```
```
 ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `SlotClone`.
    in Button (created by SlotClone)
    in SlotClone (created by Slot)
    in Slot
    in ExpoRouterLink (created by Page)
    in Page
    in Unknown (created by Route(index))
    in Route (created by Route(index))
    in Route(index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by DefaultNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by DefaultNavigator)
    in RNCSafeAreaView
    in Unknown (created by DefaultNavigator)
    in DefaultNavigator
    in Unknown (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in ThemeProvider (created by PaperProvider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by PaperProvider)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by PaperProvider)
    in PaperProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in manus(RootComponent)
```

### Expected behaviour

Not have that error?
### How to reproduce?

Here's my package.json
```
{
  "name": "manus",
  "version": "0.0.1",
  "private": true,
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "clear": "expo start --dev-client --clear",
    "android": "react-native run-android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "lint": "eslint .",
    "test": "jest"
  },
  "resolutions": {
    "metro": "0.76.7"
  },
  "dependencies": {
    "@react-native-firebase/app": "^18.2.0",
    "@react-native-firebase/auth": "^18.2.0",
    "@react-native-firebase/firestore": "^18.2.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-native-voice/voice": "^3.2.4",
    "expo": "^49.0.3",
    "expo-constants": "~14.4.2",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-paper": "^5.9.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.9",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.72.2",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "engines": {
    "node": ">=16"
  }
}

```

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.72.3
| react-native-paper    | 5.9.1
| node                            | 16.20.1
| npm or yarn                | 1.22.19
| expo sdk                     | 49.0.3

### PR DESCRIPTION
**Pull request by DimitarNestorov**
### Motivation

Closes #3988 and #3992

### Related issue

#3988

### Test plan

CI passes

### CODE REVIEW

**Review by lukewalczak — APPROVED** [review]

**Comment by RichardLindhout** [comment]
Why are we given the ref to the surface and not to the pressable?

**Comment by DimitarNestorov** [comment]
@RichardLindhout Because that's what is wrapping the button

**Comment by SleeplessByte** [comment]
@DimitarNestorov can you tell us how to get the pressable so we can focus the button programmatically among other things?

**Comment by DimitarNestorov** [comment]
@SleeplessByte opened a PR which adds `touchableRef` to Button https://github.com/callstack/react-native-paper/pull/4322

**Comment by SleeplessByte** [comment]
> @SleeplessByte opened a PR which adds `touchableRef` to Button https://github.com/callstack/react-native-paper/pull/4322

Great! FWIW this is also missing on things like dialog ☺️

**Comment by DimitarNestorov** [comment]
> this is also missing on things like dialog ☺️

Could you be more specific?

**Comment by SleeplessByte** [comment]
Definitely. Related to https://github.com/callstack/react-native-paper/issues/3912.

The modal (element with [aria-modal](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal)) should receive focus when it's shown, which means that either it, its title, its paragraph, or its first focusable element should be focussed, depending on how much content there is in the modal (aka, you don't want to focus the button if it's in a scroll container, at the bottom, and there is a scroll bar).

If the modal ref is exposed, and given a `tabindex=-1` on web, we can actually make the modal accessible, as well as [install a focus trap](https://github.com/primer/behaviors/blob/main/docs/focus-trap.md) on web (for native, https://github.com/react-native-community/discussions-and-proposals/issues/640 is still open)

Right now we can only achieve this by:

```tsx
useEffect(() => {
  if (Platform.OS !== "web" || !visible) {
    return;
  }

  // TODO: solve for other platforms
  // Wait for dialog to be mounted
  setTimeout(() => {
    const modal = document.querySelector<HTMLDivElement>(
      '[data-testid="dialog"] > [data-testid="dialog-wrapper"] > div',
    );

    if (!modal) {
      return;
    }

    modal.setAttribute("tabIndex", "-1");
    modal.focus();
  }, 1);
}, [visible]);
```

With this PR, it becomes easier as in a lot of cases we can focus the actual cancel button in `Dialog.Actions`, but installing the focustrap is hard without a reference to the node.

**Pull request merged**
