### PR TITLE
fix: button border

### PR DESCRIPTION
**Pull request by ocarreterom**
### Motivation
`outlined` buttons are taller than `contained` and `text` due to border style.

### Test plan
|before|after|
|------|-----|
|![before]|![after]|

[before]: https://user-images.githubusercontent.com/11599942/54448862-039a2b80-474d-11e9-8bf6-0a8b3a7be2a7.jpeg
[after]: https://user-images.githubusercontent.com/11599942/54448880-144aa180-474d-11e9-80df-8dd67efb69db.PNG

### CODE REVIEW

**Comment by Trancever** [comment]
Hi @ocarreterom We had an [issue](https://github.com/callstack/react-native-paper/commit/6b41e63eea69678739d3115a01f338184fb5df50) in the past and that's why we completely removed border. We would like to make sure this PR does not break it again before merging.

**Comment by ocarreterom** [comment]
@Trancever I test it on iPhone X with iOS 12.1.4 and I can't see any white border.

If the transparent border color causes some weird effects, we can set the border color to `white` in the case of `text` mode and the same background color in the case of `content` mode. Isn't it?

I would appreciate if someone could test it in other devices. 🙏

**Comment by Trancever** [comment]
Hey @ocarreterom Could you resolve conflicts? I'd like to test it next week and if everything is fine, we will merge it.

**Comment by ocarreterom** [comment]
@Trancever Done!

**Comment by Trancever** [comment]
@ocarreterom There is an issue with white bottom border on Android below 9. Could you check that?

**Comment by ocarreterom** [comment]
@Trancever If with the last change it not works, you can close this PR and I will try to refactor the component.

**Pull request closed without merging**
