### PR TITLE
fix: tests and package.json scripts so they run cross-platform

### PR DESCRIPTION
**Pull request by GollyJer**
This PR does 2 things.

1. Adds a Windows style `fixtures` for the babel plugin tests and renames the existing to reference unix.
You will find the folders `__fixtures-unix__` and `__fixtures-window__` instead of just `__fixtures__` in the `babel` directory.

2. Updates the `lint` command in `package.json` to a cross platform version.

### Motivation
I was unable to commit anything when using a Windows machine do to cross-platform issues.

### Test plan

I have tested on `Windows` and `Ubuntu`.  
**Should be tested on `macOS` but I see now reason it won't be the same as Ubuntu**.

To test run
`yarn lint`
`yarn test`

If they both run then we're good to go! 👍

### CODE REVIEW

**Comment by GollyJer** [comment]
Thanks for the feedback @satya164. I was following the feedback given to me in https://github.com/callstack/react-native-paper/issues/1309.

I've never written/edited babel plugins but I can give it a shot.
You are talking about the code in `babel\index.js`? If not can you point me in the right direction?

**Comment by satya164** [comment]
I think it needs fixing in the script that generates these mappings https://github.com/callstack/react-native-paper/blob/e5cd6fb6029396f35c7a6ca0f6ded2bb6526b64b/scripts/generate-mappings.js#L24

**Comment by Trancever** [comment]
@GollyJer Do you need any help with this? If you don't have time to work on this just let us know and we will try to finish it.

**Comment by GollyJer** [comment]
@Trancever I didn't see satya's response for some reason... 
I'd like to try and tackle it myself. I'll take a look in the next couple of days and if I can't figure it out I'll let you know.

**Comment by Trancever** [comment]
@GollyJer Any update on this?

**Comment by GollyJer** [comment]
@Trancever. I keep wanting to get to this but I'm not able to find time. Sorry for the delay in letting you know.

It would be great if you're able to take the ball. Thanks.

**Comment by Trancever** [comment]
@matkoson @haxonadora Would you like to tackle this if you have some free time? This requires windows machine so I am not sure if this is suitable for you. There is always an option to run a virtual machine though:D

**Comment by Trancever** [comment]
Closing because of the inactivity. If anybody wants to work on this feel free to submit a new PR or reopen this one.

**Pull request closed without merging**
