### PR TITLE
fix: remove cycles

### PR DESCRIPTION
**Pull request by unikvozm**
### Summary

#2336, #2233, #1867

### CODE REVIEW

**Comment by Trancever** [comment]
@unikvozm Unfortunately, this breaks the documentation :/ We can't really remove the annotations

**Comment by unikvozm** [comment]
> @unikvozm Unfortunately, this breaks the documentation :/ We can't really remove the annotations

fixed

**Comment by Trancever** [comment]
@unikvozm Hey! In the `index.tsx` file in the example app we have the following line: `YellowBox.ignoreWarnings(['Require cycle:']);`. Could you remove it? I think it is not needed anymore since the warnings are gone 👍  Once it's done I will merge the PR

**Review by Trancever — APPROVED** [review]

**Comment by Trancever** [comment]
Thanks!

**Comment by jaaywags** [comment]
Hi, it looks like this made it in release 4.5.0? I just upgraded to it but I am still receiving the error :(
image
image

**Pull request merged**
