### PR TITLE
feat: indeterminate Checkbox

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

Implement indeterminate Checkboxes according to:
https://material.io/design/components/selection-controls.html#checkboxes

### Test plan

image

### CODE REVIEW

**Comment by jaulz** [comment]
Hm, I'm not sure if that's a good idea from a developer perspective since he needs to handle strings instead of truthy/falsey values.

**Comment by satya164** [comment]
It's a minor inconvenience, but better than an inconsistent API IMO. Having two separate props which control the same thing also means that people who actually use the `indeterminate` will have to deal with 2 props in all places which can be cumbersome, and if someone wants to add this behavior to existing app, it'll require more refactoring.

**Comment by jaulz** [comment]
@satya164 just implemented the changes as suggested :) The indeterminate status for radio buttons is by the way not part of the specs (https://material.io/design/components/selection-controls.html#radio-buttons).

**Comment by ferrannp** [comment]
@satya164 can you re-check?

**Comment by jaulz** [comment]
@satya164 any chance to have a look at it for the 2.0 release?

**Comment by satya164** [comment]
merged in 3b09171aff76baddcb86f0c46685a913a4b7946d

**Pull request closed without merging**
