### PR TITLE
Add implementation of banner component.

### LINKED ISSUE #355: Banner
A banner displays a prominent message and related optional actions.

image

https://material.io/design/components/banners.html

### PR DESCRIPTION
**Pull request by Trancever**
### Motivation

Closes #355

### CODE REVIEW

**Comment by mrsteveheyes** [comment]
What's the next step for this? 

I'm looking for something like this at the moment so keen to help where I can 🙂

**Comment by Trancever** [comment]
@mrsteveheyes I will check today if everything works fine, create GIF and add few tests. After that i think we are ready for merging.

**Comment by mrsteveheyes** [comment]
Ah brilliant, thats exciting! Let me know if you want me to help with anything.

**Comment by satya164** [comment]
Ready to merge @Trancever ?

**Comment by Trancever** [comment]
@satya164 It's ready.

**Pull request merged**
