### PR TITLE
Feat/props to drawer items

### PR DESCRIPTION
**Pull request by sritharanpalani**
### Motivation
Update To the DrawerItem component Label, Icon, and TouchableRipple

- Add a style to Label

- RippleColor props to TouchableRipple 

- IconSize to Left Icon

### Test plan

Add Drawer.Item component with addtional props 

`<Drawer.Item
      label="First Item"
      labelStyle={{fontSize: 20}}
      iconSize={29}
      rippleColor={'transperant'}
 />`

### CODE REVIEW

**Comment by jaysbytes** [comment]
Is this change required by the community? We should first discuss if this change is needed. Everyone wants to change something in the lib, which fits some specific need, but we need to discuss if it is good from the library perspective and follows material design guidielines

**Comment by sritharanpalani** [comment]
@jaysbytes I have added an example for this change! 
these additional props have not affected the guidelines provided by Material by default (every additional props are optional ) 
Screen Shot 2019-09-09 at 12 54 08 PM

**Comment by sritharanpalani** [comment]
@ferrannp  hey you need a any clarification from my side!

**Comment by sritharanpalani** [comment]
Hello Team
We use react-native-paper extensively and would love to have this change merged.  This change is completely backward compatible. Please let me know if I can answer any questions or make any changes to accelerate this PR. Thanks so much.

**Comment by Trancever** [comment]
@sritharanpalani We are having a hard time deciding if those additional props are needed. What exactly do you want to achieve with a `rippleColor` prop? In example I see you set it to 'transparent', do you want to remove the ripple effect completely?

**Comment by sritharanpalani** [comment]
@Trancever The main purpose is to customize rippleColor / remove it. by having this additional prop we can achieve more design level aspects effects.

Thanks @Trancever for the effort

**Comment by Trancever** [comment]
@sritharanpalani We think that the proposed changes allows for too much customizability. We want to keep the API of the components as easy and approachable as possible and proposed changes allows making the component not MD guidelines compliant e.g. no ripple effect at all on press.

What we suggest is to create your own `Drawer.Item` component that will be compliant with your design system.  You shouldn't be afraid of the code duplication and increased bundle size, because not used paper components are not included into the final bundle thanks to the babel plugin that we provide.

**Comment by sritharanpalani** [comment]
thanks @Trancever

**Pull request closed without merging**
