### PR TITLE
Platform-specific RadioButton and CheckBox

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

Animations for RadioButton and CheckBox are turned off for any other platform than Android so far. Since there's anyway an separate iOS component (via extension) we can remove the check and at the same time provide the animations for web platform as well.

### Test plan

n/a

### CODE REVIEW

**Comment by satya164** [comment]
Actually I'm thinking if we should export these components as `CheckboxAndroid` and `RadioButtonAndroid` so people can use it on other platforms like iOS if they really want it. In that case, it'll be better to turn the animation off on iOS with `Platform.OS === 'ios` instead of `Platform.OS !== 'android` :)

BTW are you on our discord? You should join it if you aren't!

**Comment by jaulz** [comment]
Good idea. That would also follow the conventions of React Native components. Shall I come up with an implementation or are you already working on it?

P.S.: just joined your Slack channel :-)

**Comment by Trancever** [comment]
We switched from slack to discord recently, here is the link https://discord.gg/mYACqX

**Comment by ocarreterom** [comment]
How about to implement this pattern?
`RadioButtonIOS` -> iOS style
`RadioButtonAndroid` -> Android (and default for web) style
`RadioButton` -> if `Platform.os === 'ios'` return `RadioButtonIOS` else return `RadioButtonAndroid`

**Comment by ferrannp** [comment]
@jaulz & @satya164 is this PR still valid?

**Comment by jaulz** [comment]
@ferrannp yes, it is still valid. These changes will allow you to choose from platform specific components which gives you for example the opportunity to use `CheckboxAndroid` on iOS. If you simply require `Checkbox` or `RadioButton` it will automatically use the correct component for the platform but falls back to Android (e.g., for web platform)

**Comment by satya164** [comment]
It was merged in https://github.com/callstack/react-native-paper/commit/b9631580b5db79ce84d6b360a177d4c37414b36f

**Comment by jaulz** [comment]
@satya164 thanks! Though it seems you missed the exports in index.js :-)

**Pull request closed without merging**
