### PR TITLE
fix: NotificationsRoute causing error

### PR DESCRIPTION
**Pull request by dragonxp**
Missing NotificationsRoute and notifications key in SceneMap

### CODE REVIEW

**Comment by lukewalczak** [comment]
Hey @dragonxp, could you please rename the commit to follow the [commit naming convention](https://github.com/callstack/react-native-paper/blob/main/CONTRIBUTING.md#commit-message-convention)?

**Comment by dragonxp** [comment]
> Hey @dragonxp, could you please rename the commit to follow the [commit naming convention](https://github.com/callstack/react-native-paper/blob/main/CONTRIBUTING.md#commit-message-convention)?

Done

**Comment by lukewalczak** [comment]
I still can see that commit is named [Fixed NotificationsRoute causing error](https://github.com/callstack/react-native-paper/pull/3326/commits/5b109d4d825527a4fd17badb67fb5aad78ab0fff).

**Comment by dragonxp** [comment]
Fixed now [fix: NotificationsRoute causing error](https://github.com/callstack/react-native-paper/pull/3326/commits/c4fffb7f6de604dbda85690fd4d5835b1fff1e67)

**Review by lukewalczak — APPROVED** [review]
Thanks!

**Pull request merged**
