### PR TITLE
Customize Searchbar icons 

### PR DESCRIPTION
**Pull request by belgamo**
### Motivation
Provide a way to custom the `icon` and `clearIcon`. This feature changes the way how we handle the icons, so it will be treated as `leftIcon` and `rightIcon`. However, `icon` and `clearIcon` still work, but they are deprecated.

Based on #1705

### CODE REVIEW

**Comment by belgamo** [comment]
#2001

**Comment by Trancever** [comment]
Could you provide me an example of how Material Design searchbar handles the loading state? I've checked the guidelines and it looks like they show loading indicator under the searchbar, in the autocompletion zone.

Before we merge this PR we want to make sure this is something that MD really recommends. If they don't, then users will have to build it themselves.

**Comment by belgamo** [comment]
> @belgamo Could you provide me an example of how Material Design searchbar handles the loading state? I've checked the guidelines and it looks like they show loading indicator under the searchbar, in the autocompletion zone.
> 
> Before we merge this PR we want to make sure this is something that MD really recommends. If they don't, then users will have to build it themselves.

I don't have an example, but I think the icons should be customizable. The user can use any icon as a "clear icon", so, it's better to have it as "right icon" or "end icon", for example. The button with loading state that the `react-native-paper` have implemented is not documented in guidelines as well.

**Comment by brunohkbx** [comment]
@belgamo can you please rebase this one?

**Comment by Trancever** [comment]
@belgamo I am not sure if Paper needs this change. It will not only add more complexity to the component but probably not many users will benefit cause it's not how this component should be used. According to MD Guidelines, search indicators should be placed under the searchbar and that's what Google's apps do as well.

On the other hand, the implementation of the component is not very complex so if you really need this change in your project I would suggest using patch-package.

Anyway, thanks for your contribution, it's still very valuable even tho we don't merge the PR 👍 🙏

**Pull request closed without merging**
