### PR TITLE
Fix: button animation

### PR DESCRIPTION
**Pull request by logustra**
### Motivation
https://github.com/callstack/react-native-paper/issues/1678

### Test plan
Nothing visual has changed

### CODE REVIEW

**Comment by Trancever** [comment]
@logustra Is it possible to animate elevation using native driver now?

**Comment by vicary** [comment]
From https://github.com/callstack/react-native-paper/issues/959#issuecomment-477961362, we should be cautious to put a simple `true`. Something like what ad516cca4326bfa55a2859d85817de11c54c36e8 does should be more sensible, because the referenced issue only wants to get rid of a warning where `undefined` should be explicitly `false`.

**Comment by logustra** [comment]
@Trancever 
I have checked it with expo 32 and got an error on iOS and I fixed it like you did on https://github.com/callstack/react-native-paper/commit/ad516cca4326bfa55a2859d85817de11c54c36e8

**Comment by Trancever** [comment]
@logustra I believe it's safe to pass true for iOS cause we are dropping support for RN < 0.60 anyway.

**Pull request merged**
