### PR TITLE
feat: IconButton

### PR DESCRIPTION
**Pull request by jaulz**
### Motivation

Sorry for creating this one again but I stumbled again the same requirement that it's really helpful to have an Icon component that accepts a string (i.e. icon name) or alternatively a source object. Having the same as a touchable component makes it even better :-) It keeps the styling consistent across my app.

### Test plan

n/a

### CODE REVIEW

**Comment by satya164** [comment]
I think exporting `TouchableIcon` is fine, though we should rename it to `IconButton` or something before exporting.

Regarding exporting `Icon`, I'm not convinced that it's useful for normal projects which aren't libraries. Let's discuss it on our discord.

**Comment by gawrysiak** [comment]
I agree with @satya164 on the standard `Icon`. Being able to display an object or component instead is not really what I'd normally expect from a Material Design Icon component. That's a side effect, doesn't really bring any direct value to the original vector icons lib.

**Comment by ferrannp** [comment]
@jaulz did you rename?

**Comment by jaulz** [comment]
If you are okay, I can for sure refactor and rename it. Is `IconButton` the final decision?

**Comment by jaulz** [comment]
@ferrannp done :)

**Comment by jaulz** [comment]
Yep, will do so in the coming days.

**Comment by jaulz** [comment]
@ferrannp can you please check? Though I'm not sure why the documentation is not updated since I can see it locally.

**Comment by satya164** [comment]
Thanks for the PR. I'll take care of merging.

**Comment by satya164** [comment]
Merged in 0108b23d33f9d215f83414f7aa289bb8d7a0bc83

**Pull request closed without merging**
