### PR TITLE
fix: cyclical imports

### PR DESCRIPTION
**Pull request by raajnadar**
### Motivation

Remove cyclical imports in

Appbar
FAB
RadioButton
ToggleButton

### Test plan

Run the example app no warning in console as well as no yellowbox warning in the application.

### CODE REVIEW

**Comment by Trancever** [comment]
@raajnadar I am ok with merging this, however, I would prefer to merge a solution that is not based on class extending. I know that it won't cause any issues in this case, that's why I'll keep this open for a couple of days and if no one provides another solution I will merge this PR.

**Comment by Trancever** [comment]
@raajnadar Unfortunately this breaks the documentation. Could you take a look at it when you have some free time?

**Comment by raajnadar** [comment]
Ok

**Comment by listepo** [comment]
any news?

**Comment by Trancever** [comment]
@listepo Not really. We don't prioritize fixing it, but if someone comes up with a solution that doesn't break the functionality and documentation we are more than happy to merge it.

**Comment by raajnadar** [comment]
I will fix it, need some time to figure out the issue! As well as a new component also started throwing the warning.

**Comment by pang0018** [comment]
Thank you @raajnadar for doing this!

**Comment by frey-sw** [comment]
Up! thanks everyone involved on this fix

**Comment by pang0018** [comment]
@Trancever can this one be merged?

**Comment by raajnadar** [comment]
@Trancever I tried fixing the docs issue but I don't have much knowledge of how component docs work! Can you ask someone from core team to investigate.

**Comment by pke** [comment]
> @listepo Not really. We don't prioritize fixing it, but if someone comes up with a solution that doesn't break the functionality and documentation we are more than happy to merge it.

According to the checks the docs built ok. Can't we trust the build check?
What exactly is broken with the docs?

**Comment by arniu** [comment]
How about just assigning the static properties in `index.ts` without class extending?

Take `ToggleButton` for example: 

```typescript
import React from 'react';

// ToggleButton.tsx
class ToggleButton {
    static Row: React.ComponentType;
}

// ToggleButtonRow.tsx
class ToggleButtonRow extends React.Component {
    render() {
        return null;
    }
}

// index.ts
ToggleButton.Row = ToggleButtonRow;
```

**Comment by raajnadar** [comment]
@arniu can you explain your code in detail?

**Comment by arniu** [comment]
In face, the class extending in `index.ts` did nothing except assigning static properties.
And why not directly [assign them](https://www.typescriptlang.org/play/index.html?ssl=18&ssc=36&pln=18&pc=41#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCrQBsUBnBuAFQgHN3akAhAVxgwIAOzhIAHjCTCAJs2ToYAOgDCuSMOnwA3lTj64AekNwAIkkzBNcFHAYwUMYGjhgcYJLACecABaekPQN7R2dECAB3AC5EYmU1cBEtFi8PCmpKAzgiWU8ACgBKOF1MrIMiGD4oUWE+Wlp0rIBfKhaMukZmNk5ufkERBEixSWk5WMVVdSThHSD9HJl8opKy8qRK6rha+saDNraqYzgAQVkbJmB2UWB4fyI4KzgAAytF8SUYBieqbq5eASEwiUgwicAAvKwOH8+oCQekgA)?

**Comment by frey-sw** [comment]
Up?

**Comment by Trancever** [comment]
@satya164 Please correct me if I am wrong. If we fix it in a way that @arniu suggested (assigning statics in index.tsx where we export the components) then it will break in production when used together with babel plugin, no?

**Comment by arafatzahan** [comment]
is these pr dead?

**Comment by samuhay** [comment]
Still active we need to fix this. Thank you.

**Comment by raajnadar** [comment]
Closing the PR because it is dead!

**Pull request closed without merging**
