### PR TITLE
feat: Styling of labels in FAB.Group

### PR DESCRIPTION
**Pull request by haakandev**
### Summary

This PR adds properties for the FAB.Group actions to allow for custom styling of the FAB.Group labels.

### Test plan

Provide `labelTextColor` and `labelStyle` properties in the FAB.Group's `actions` array.

### CODE REVIEW

**Comment by andreialecu** [comment]
I recently ended up using patch-package to add this and I was just about to open pretty much the exact same PR.

Please consider merging this.

**Comment by hefberk** [comment]
Hi,
Thank you for this patch, but I can't make it work.
I replace react-native-paper version in package.json like this :
"react-native-paper": "https://github.com/haakandev/react-native-paper.git#feat/fab-group-styling"
In my node_modules I can see the patch.
But when i do 
<FAB.Group labelTextColor={'#FF0000'}/>
Text is always black.
Don't work with labelStyle too.
I don't understand, your code seems ok, does it work for you ?
It would be great to implement selectable=false on label to have good cursor on web.

**Comment by hefberk** [comment]
property fontSize doesn't seems working

**Comment by haakandev** [comment]
> property fontSize doesn't seems working

Hi @hefberk - the label component as is just uses a standard react-native-paper `Text` element. The `labelStyle` is actually for the wrapping `View` component. If desired, the change could be modified to take a `labelTextStyle` prop instead of `labelTextColor` to allow further customising of the label text.

**Review by lukewalczak — APPROVED** [review]
@haakandev thanks!

**Pull request merged**
