### PR TITLE
Bump react-native-safe-area-view to 1.0.0

### LINKED ISSUE #1353: Update react-native-safe-area-view dependency
## Environment

react-native > 0.60.5
react-native-paper 2.16.0

## Description

react-native-safe-area-view is currently listed as version "^0.12.0". The implementation of the `SafeView` component in 0.12.0 uses `componentWillReceiveProps`, which on react-native 0.60+ displays a YellowBox warning of the following:

```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: SafeView

Learn more about this warning here
```

react-native-safe-area-view has released version 0.14, which no longer uses componentWillReceiveProps and thus avoids this Warning popping up. 

However, more broadly, yesterday (September 26th), react-native-safe-area-view also just updated to version 1.0.0, which might also be worth updating the usage in this package

## ~~Reproducible Demo~~

Any usage of a component that uses safe-area-view should trigger this warning.

### PR DESCRIPTION
**Pull request by benoitdion**
Also bump react-native-safe-area-context to 0.5.0.
Update all instances of react-native's SafeAreaView to the community version.

### Motivation

Fixes #1353

### Test plan

- Manual regression of the `AppBarHeader`, `BottomNavigation`, `FABGroup`, `Modal` and `Snackbar` components.
- Updated snapshots.

### CODE REVIEW

**Comment by benoitdion** [comment]
@satya164 makes sense. How are you thinking about introducing linking native code?

**Comment by Trancever** [comment]
@satya164 Any idea what to do with it?

**Comment by satya164** [comment]
@Trancever lets talk about it in office

**Comment by wesleyschneider** [comment]
+1

**Comment by benoitdion** [comment]
hey @satya164 @Trancever, did anything come out of your discussion?

**Comment by satya164** [comment]
We don't want to add native dependencies at the moment. But https://github.com/ptelad/react-native-iphone-x-helper is a good alternative which we should switch to.

**Comment by benoitdion** [comment]
Unfortunately, https://github.com/ptelad/react-native-iphone-x-helper has no android support and is far less battle-tested. `react-native-safe-area-view` has expo support so it doesn't feel that crazy to add as a dependency.

**Comment by satya164** [comment]
Won't Android be handled with StatusBar.currentHeight (also Constants.statusBarHeight in Expo)?

We have like only 2-3 components needing it. I think it's fine for now.

I also want to wait till react native safe area context matures a bit, there are some issues right now which we have encountered in React Navigation.

**Comment by benoitdion** [comment]
`Snackbar` and `FABGroup` seem to rely on the actual `SafeAreaView` component for bottom safe areas

**Comment by satya164** [comment]
I think it's relatively uncommon to have a bottom safe area on Android, so it'll still cover 99% of use cases. We need to have option to override it to address that 1% of case.

**Comment by andreialecu** [comment]
@Trancever @satya164 - this PR or a variant of it is now necessary for RN 0.62+ support. It results in warnings for `react-navigation` because of the obsolete `react-native-safe-area-view` dependency of `react-native-paper`. See discussion in #1781.

The warnings are also particularly long and add a lot of noise to logs:

```
[Thu Apr 23 2020 14:53:33.399]  WARN     %s: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. ReactNativeFiberHostComponent 
    in SafeView (at withOrientation.js:54)
    in withOrientation (at BottomNavigation.tsx:750)
    in BottomNavigation (created by Context.Consumer)
    in Context.Consumer (created by ThemedComponent)
    in ThemedComponent (created by withTheme(BottomNavigation))
    in withTheme(BottomNavigation) (at MaterialBottomTabView.tsx:48)
    in MaterialBottomTabView (at createMaterialBottomTabNavigator.tsx:42)
    in MaterialBottomTabNavigator (at main-screen.tsx:48)
    in MainScreen (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in CardContainer (at CardStack.tsx:531)
    in CardStack (at StackView.tsx:420)
    in KeyboardManager (at StackView.tsx:418)
    in Context.Consumer (at StackView.tsx:416)
    in StackView (at createStackNavigator.tsx:67)
    in StackNavigator (at App.tsx:140)
    in MainNavigation (at SceneView.tsx:98)
    in SceneView (at useDescriptors.tsx:125)
    in DrawerView (at DrawerView.tsx:210)
    in DrawerView (at createDrawerNavigator.tsx:42)
    in DrawerNavigator (at App.tsx:176)
    in DrawerNavigation (at App.tsx:239)
    in Query (at graphql.tsx:5842)
    in GetCurrentUserComponent (at App.tsx:236)
    in App (created by inject-with-UserStore-SettingsStore(App))
    in inject-with-UserStore-SettingsStore(App) (at main.tsx:50)
    in Main (at renderApplication.js:45)
```

**Pull request closed without merging**
