### PR TITLE
Update SearchBar.js

### PR DESCRIPTION
**Pull request by shcheuk**
icon props is fixed to be 'search' only if onIconPress is not defined. It should change according to the string  provided to icon props

### CODE REVIEW

**Comment by ferrannp** [comment]
@shcheuk it looks good. Can you fix lint?

**Comment by shcheuk** [comment]
image
These?

**Comment by gawrysiak** [comment]
@shcheuk check out https://circleci.com/gh/callstack/react-native-paper/1536?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for details

**Comment by shcheuk** [comment]
￼￼￼￼image
line 12,13,14 seems not related to this fix. They seems all related to using .ts syntax in .js

**Comment by shcheuk** [comment]
oh thx, will do tmr.

**Comment by satya164** [comment]
@shcheuk run `yarn lint --fix` in a terminal and it should fix the errors. the above errors are from typescript which is not relevant since we don't use typescript.

**Pull request merged**
